name: Trivy Scan

on:
  schedule:
    - cron: "12 13 * * 1"
  workflow_run:
    workflows: ["Docker Publish"]
    types: [completed]

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/${{ github.repository }}:latest
          format: template
          template: '@/contrib/sarif.tpl'
          output: trivy-results.sarif
      - name: upload trivy results
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: trivy-results.sarif
